### ISSUE TITLE
Determine packages to focus on in comparative analysis

### ISSUE THREAD

**Issue by InMatrix** [flutter/uxr#10]
Update: Please see our preliminary decision in [this comment](https://github.com/flutter/uxr/issues/10#issuecomment-820669779) posted on Apr 15, 2021.

This is a prerequisite of #7. I'm proposing the following criteria for inclusion in the comparative analysis:
- The package supports (or has a concrete plan for supporting) the navigation scenarios considered common and important (#4)
- The package author is engaged in this research and is willing to contribute code snippets for the comparative analysis
- The package represents a distinctive approach towards simplifying common usage of Navigator 2.0. In other words, we might only examine one of the several packages that are similar in the way they build on top of Navigator 2.0 to maximize what we learn from the research. 
- The package is relatively popular based on signals such as the popularity score on pub and the number of stars/contributors on Github.

**Comment by jackkim9** [comment]
**Status update:**

The package supports (or has a concrete plan for supporting) the navigation scenarios considered common and important (#4).
- Following packages currently support all six scenarios from #4: **auto_route**, **qlevar_router**, **routemaster**, **vrouter** ([Preliminary Comparative Analysis](https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis))

The package author is engaged in this research and is willing to contribute code snippets for the comparative analysis.
- Authors from **beamer**, **fluro**, **routermaster**, and **vrouter** have been very active in the discussions (#4, #5, #6).
- **Vrouter**'s author has already provided [code snippets](https://github.com/flutter/uxr/issues/6#issuecomment-781730369) addressing the common navigation scenarios identified in [Storyboards v1](https://github.com/flutter/uxr/blob/master/nav2-usability/storyboards/%5BPublic%5D%20Flutter%20Navigator%20Scenarios%20Storyboards%20v1.pdf).
- Most package authors have expressed interest in submitting code snippets via email and on GitHub.

The package represents a distinctive approach towards simplifying common usage of Navigator 2.0. In other words, we might only examine one of the several packages that are similar in the way they build on top of Navigator 2.0 to maximize what we learn from the research.
- We are currently looking into this. (CC: @johnpryan @chunhtai @InMatrix )
- Please share if any community member has any thoughts on packages with distinct approaches.

**Comment by johnpryan** [comment]
I would also like to study page_router's API as well, even though it
doesn't support nested routing yet.

**Comment by esDotDev** [comment]
I have released my `nav_stack` packages which I think might be worthy of some consideration:
https://pub.dev/packages/nav_stack

It's very fresh, and not really production ready, but I think there is enough there to review for now.

**Comment by nguyenxndaidev** [comment]
> * Following packages currently support all six scenarios from #4: **auto_route**, **qlevar_router**, **routemaster**, **vrouter** ([Preliminary Comparative Analysis](https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis))

`Navi` 0.2.0 will support all scenarios soon in the simplest API. I am working on it and nearly reach to release. I hope I can release it this week and update with code snippets for the complex nested scenarios. All other scenarios are already in the PR https://github.com/flutter/uxr/pull/38 since 11 days ago.

The distinct approach of `Navi` is that:
* No global configuration at all. Each stack manages only the URL part of itself. The deepest nested stacks will combine all URL parts into a single one.
* No need to provide configuration for the root router. All logic is moved to child routers to reduce a lot of complexity in both usage side and package implementation side.
* The API is just a single widget with minimal properties because each the widget only need to manage the part of itself. It doesn't need to know about parent or child stacks.

**Comment by InMatrix** [comment]
I have an update on this issue. Please see the note below. 

# Objective  

The next steps of our research involve a detailed feature and usability evaluation of specific routing packages. We hope the results will make it easier for Flutter users to decide 1) whether they need the full flexibility of the Navigator 2.0 and Router API (referred to as “Navigator 2.0” below) and the complexity that comes with it, or 2) which routing package could satisfy their app’s requirements with the least amount of effort. In addition, we hope this evaluation can help routing package authors, especially those experimenting with new API designs, make better API design choices and evolve their existing APIs as needed. 

To ensure both the depth of our research and the ability to provide useful advice to the Flutter community by the end of May, we plan on comparing just 3 packages in the detailed evaluation for now. After the results are published, we might consider evaluating additional packages if they present solutions to address important limitations found in the first set of packages we evaluate. We aim to publish the full design of the study so that a motivated community member can replicate the study for additional packages in the future. 


# Selection criteria

As we mentioned in issue #10, we were looking at 4 aspects when selecting routing packages for the detailed evaluation. We’ve since expanded on these 4 aspects with specific metrics and attributes, described below: 

*   **Scenario coverage**: The package supports (or has a concrete plan for supporting) the navigation scenarios considered common and important ([#4](https://github.com/flutter/uxr/issues/4)). 
    *   Metric: # of scenarios covered according to the [package scenario support comparison table](https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis)
*   **Author engagement**: The package author is engaged in this research and is willing to contribute code snippets for the comparative analysis.
    *   Metrics: # of snippets provided, commitment to evolve API design based on study results, participation in discussions
*   **API design**: The package represents a distinctive approach towards simplifying common usage of Navigator 2.0. In other words, we might only examine one of the several packages that are similar in the way they build on top of Navigator 2.0 to maximize what we learn from the research. Below are a list of API design choices we’re currently considering:
    *   Routing paradigm: path-driven, state-driven, hybrid (see [this discussion](https://github.com/flutter/uxr/issues/15))
    *   Compatible with MaterialApp.router: does the API still use the MaterialApp.router interface or replaces it? 
    *   Custom transition animations: how much control does the developer have over page transition animations. Can the developer define custom pages or just use MateiralPage? 
    *   Modularity for hierarchical routing: does the package allow routes to be defined in separate libraries or combined? 
    *   Code generation: does the API relies on code generation or not? 
    *   Additional factors we're considering to check
        *   Compatible with WidgetApp and CupertinoApp
        *   Handles deep links on Android, iOS, and web browsers
        *   Does the Browser button do [reverse chronicle navigation](https://material.io/design/navigation/understanding-navigation.html#reverse-navigation) or upward navigation?
*   **Popularity**: The package has gained some traction in real world usage. We understand this will put new packages at a disadvantage, but for the purpose of providing immediately useful advice to Flutter users in the short term. We are intentionally making this tradeoff between relatively more mature packages and new packages that are still experimental in nature. We’re looking at the following metrics of popularity:
    *   Pub.dev popularity score
    *   Pub.dev likes
    *   Github stars

# Shortlisted packages

We tentatively shortlisted 3 packages based on the criteria described above. The rest of this section shows the data that has informed our decision. Note, some data points are still missing, and we hope the package authors can help us fill in the gaps. 


## vrouter

[Pub](https://pub.dev/packages/vrouter) | [Github](https://github.com/lulupointu/vrouter) | [Documentation](https://vrouter.dev/guide)

What research questions does studying this package allow us to answer?
*   Do Flutter users miss a declarative (state-driven) API when evaluating vrouter?

**Scenario coverage**: [6/6](https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis)

**Author engagement**

*   _Scenario code_: [Merged](https://github.com/flutter/uxr/tree/master/nav2-usability/scenario-code) except nested routing
*   _Participation in discussions_: Active
*   _Possibility to evolve API design_: Confirmed

**API design**

*   _Routing paradigm_: Path-driven
*   _Compatible with MaterialApp.router_: No, it uses VMaterialApp which wraps MaterialApp.router
*   _Custom transition animations_: Yes
*   _Modularity for hierarchical routing_: Seems to be possible but hasn’t been implemented per [this comment](https://github.com/flutter/uxr/issues/35#issuecomment-813898956)
*   _Code generation_: No

**Popularity** (Updated on Apr 15, 2021)

*   _Pub.dev popularity_: 84%
*   _Pub.dev likes_: 74
*   _Github stars_: 58

## beamer

[Pub](https://pub.dev/packages/beamer) | [Github](https://github.com/slovnicki/beamer) |  [Documentation](https://github.com/slovnicki/beamer)

Research questions specific to the package

*   Do Flutter users see value in using declarative, state-driven routing in sign-in flows?

**Scenario coverage**: [6/6](https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis)

**Author engagement**

*   _Scenario code_: Example code for the first three scenarios have been [merged](https://github.com/flutter/uxr/tree/master/nav2-usability/scenario-code)
*   _Participation in discussions_: Active
*   _Possibility to evolve API design_: To be confirmed

**API design**

*   _Routing paradigm_: Hybrid. URL is primary, but state can be used for declarative routing within a BeamerLocation (see [this comment](https://github.com/flutter/uxr/issues/15#issuecomment-793749395)). 
*   _Compatible with MaterialApp.router_: Yes, it provides a custom routeInformationParser and a custom routerDelegate for MaterialApp.router.
*   _Custom transition animations_: Yes
*   _Modularity for hierarchical routing_: Unknown
*   _Code generation_: No

**Popularity** (Updated on Apr 15, 2021)

*   _Pub.dev popularity_: 90%
*   _Pub.dev likes_: 184
*   _Github stars_: 125

## auto\_route

[Pub](https://pub.dev/packages/auto_route) |  [Github](https://github.com/Milad-Akarie/auto_route_library) | [Documentation](https://autoroute.vercel.app)

Research questions specific to the package
*   Do Flutter users feel comfortable using code generation?

**Scenario coverage**: [6/6](https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis)

**Author engagement**

*   _Scenario code_: Example code for the first two scenarios are [to be reviewed](https://github.com/flutter/uxr/pull/36)
*   _Participation in discussions_: No
*   _Possibility to evolve API design_: To be confirmed

**API design**

*   _Routing paradigm_: Hybrid. URL is primary, but state-driven declarative routing is supported for local flows ([doc](https://autoroute.vercel.app/advanced/declarative_routing)).  
*   _Compatible with MaterialApp.router_: Yes, the package generates a custom routerDelegate and a custom routeInformationParser.
*   _Custom transition animations_: Yes
*   _Modularity for hierarchical routing_: Unknown
*   _Code generation_: Yes

**Popularity** (updated on Apr 15, 2021)

*   _Pub.dev popularity_: 97%
*   _Pub.dev likes_: 650
*   _Github stars_: 487

# Reasons for not selecting other packages

As mentioned earlier, the Flutter team doesn’t have bandwidth to evaluate more than 3 packages in depth and still reach our goal of providing the Flutter community with some guidance on routing API choices by the end of May this year. Here, we’d like to briefly explain why other packages didn’t make the shortlist for the full evaluation this round. 



*   Popularity below threshold or new package as of April 15
    *   qlevar\_router, navi, flit-router, flouter, page\_router
*   Lack support for multiple routing scenarios
    *   fluro, flow\_builder
*   Have a much larger scope than routing
    *   flutter\_modular

Still, we’d like to thank all the package authors who have contributed to this research project so far, especially the author for navi and the author for qlevar_router, both have submitted code examples. 

# Feedback

We welcome your feedback on our selection process, especially on any factual errors in the information presented above. We intend to move forward with evaluating the three packages on the shortlist if no justified objections are received by **April 22, 2021**.

**Comment by nguyenxndaidev** [comment]
Thanks @InMatrix for the info!

> To ensure both the depth of our research and the ability to provide useful advice to the Flutter community by the end of May

How will flutter team make sure that the advice you will provide by the end of May doesn't affect other packages negatively? It would be nice if users can compare solutions equally and not be influenced by this selection.

Will the advice be actively updated to add more packages after this research? If yes, how?

**Comment by InMatrix** [comment]
Thank you for your questions, @nguyenxndaidev. Please see my inline response below, on behalf of the Flutter team members working on this research project. 

> Will the advice be actively updated to add more packages after this research? If yes, how?”

The short answer is yes, we’d like to keep any advice we give to Flutter users up to date. How soon we will revisit our initial advice is likely to be influenced by the feedback users give us on how useful our advice is. 

Though we might not be able to keep working on this project at the current level of involvement after Q2, we intend to maintain a space for discussing routing API design for interested parties after the completion of this study and find ways to enable community members to replicate the kinds of API evaluations for additional packages based on the protocols and examples we will have developed.  

> How will flutter team make sure that the advice you will provide by the end of May doesn't affect other packages negatively? It would be nice if users can compare solutions equally and not be influenced by this selection.

We would like the results of this research to benefit two types of Flutter users in two different ways. First and foremost, there are users who don’t have the time or the interest to compare a dozen of routing packages on their own. To serve those users, we would like to point them to one of the packages we believe can solve their problem relatively easily based on our research. Without any guidance, those users might just go with the most popular option at the time they are looking or end up making unnecessary compromises in their apps. We are hoping that despite our narrowed scope and our capacity to only evaluate 3 packages this time, this study will help this group of users get past the hurdle of choosing a package and get back to focusing on developing their app.

There is a second group of users who like to deeply understand what’s available and perform a serious evaluation themselves. Instead of providing those advanced users with simple advice, this research can potentially give them a framework and points of reference for their own evaluations. It’s our sincere hope that assessing the handful of packages on our shortlist can help establish the “prior art” in high-level Flutter routing API design. With this baseline set, it’s easier for a truly innovative new package to show that they’ve improved upon the prior art in specific ways. We believe this is necessary to avoid reinventing the wheel and save the Flutter community from being overwhelmed by too many choices without substantial differences.

**Comment by idkq** [comment]
> Without any guidance, those users might just go with the most popular option at the time they are looking

Very true, it happens a lot. Flutter's team recommendation, especially if it is written on the official page, carries a lot of weight.

**Comment by esDotDev** [comment]
It does feel like this is maybe a year or so premature, there really hasn't been time for community to really coalesce over favored options, it's more just a first-to-market kind of situation. 

Maybe the team can revisit this in a calendar yr or so, and do a similar vetting of what is out there.

**Comment by nguyenxndaidev** [comment]
> it's more just a first-to-market kind of situation.

I also think like that. Especially for the first research, when all packages are new and none of them are mature enough to give people the right advices.

IMHO, the first research we are doing right now and the result to end of May is somehow not really the truth.

I agree that, this research's result will help community a lot to come back to development. But I think it should be only the result for a short term.

I would suggest to revisit this research at the end of this year, when most packages become quite mature.
I feel that end of this year is not too long and not too short for both package authors and end developers. 6 months after this research are enough for all packages to be ready for a real comparison with their full strength. The comparation right now could not produce a good result. However, it is a very good starting point for all parties, so they can prepare for the next revision.

**Comment by InMatrix** [comment]
I understand the desire to arrive in the best possible solution from this research. I think we probably need to consider splitting this project into two tracks: a short-term track for addressing the immediate needs of Flutter users and a long-term track for systematically designing a better routing system for Flutter.    

Delivering value to Flutter users in the short term is important, because this project was started in response to weekly, if not daily, complaints about the complexity of Navigator 2.0. People have been waiting for some practical advice from the Flutter team and other educators in the Flutter community. So we have to time box this initial investigation and perhaps settle on a solution that is good but not perfect for now.

Once the short-term goal is met, we'd love to continue working with package authors to address a set of long-term API design questions some discussions in this repo have surfaced. To scale the evaluation process, we might need to onboard a few community members as usability evaluators, proficient in applying [the rubrics](https://github.com/flutter/uxr/wiki/API-Usability-Evaluation-Guide) to an API design. Hopefully this will become easier once we publish results from evaluating the first set of packages later this quarter.

**Comment by idkq** [comment]
Thanks @InMatrix your contribution, leadership and execution has been amazing. Truly appreciate the quick response to this issue and the careful consideration to the complexities it involves.

This is definitely not an easy task, even though navigating screens had been traditionally more or less straightforward. I believe that there are better long term architectural designs that could help here, but significant investment is needed for sure.

**Comment by nguyenxndaidev** [comment]
@InMatrix to save work for flutter team when we scale for the long-term, I would suggest to write testing for all scenarios. Package authors are not allowed to change the testing code. Their provided code must pass all the tests before starting review process.
