### ISSUE TITLE
Create a chat room for Nav 2 usability research

### ISSUE THREAD

**Issue by InMatrix** [flutter/uxr#11]
We plan on creating a chat room on Flutter team's Discord server to complement discussions in this Github repo.

**Comment by johnpryan** [comment]
On our web page we link to the[FlutterDev](https://discord.com/invite/N7Yshp4) discord server, so I probably need to ask around there.

**Comment by InMatrix** [comment]
@johnpryan Can we create a channel on the Flutter discord server like the `adopt-a-widget` channel? We can archive the channel once this project is done.

**Comment by johnpryan** [comment]
I did ask about this in the server-support room, but started to doubt if it was the right Discord server. Hopefully I'll get a response soon.

**Comment by InMatrix** [comment]
@johnpryan Thanks! I follow up there, too.

**Comment by pedromassangocode** [comment]
Why not a GitHub Discussion room?

**Comment by InMatrix** [comment]
Chat channel has been created at https://discord.com/channels/608014603317936148/813579416264507422.

We still expect to use the issues section in this repo as the main communication channel, especially for tracking planned research work. 

@pedromassangocode We just wanted to use what's already available in Flutter team's public communication infrastructure. The Discussion feature is not currently enabled by any of the repos under `/flutter`.
