### ISSUE TITLE
About Flutter UX research Q4 2023

### ISSUE THREAD

**Issue by FMorschel** [flutter/uxr#115]
I'm not sure this is the right place to put this, please help me with this.

I would like to suggest a few things. 

1. **A place inside the research to give feedback about the questions asked**. I needed to come over here to give you my feedback on the actual research by searching on Google because I didn't even know this repo existed.
2. **Add a reference to issues for questions that talk about new/existing features** so if people want more information they can go there. (Mainly about the opinions on the new features. If the person has no familiarity with the feature from any other language, this is a way for them to get to know the feature and how it would work in Dart by following the thread on GitHub.
3. **Spread the word about the survey**. Make sure that the survey is easy to find. Post it on X (Twitter), Discord, etc, or even place it on pub.dev/flutter.dev like a cookie snack bar. Once I misclicked on "No" on my IDE and could not find where to answer it again.

**Comment by khanhnwin** [comment]
Hi @FMorschel! Thank you for submitting these suggestions. Sending this over to our UXR for review.

**Comment by jayoung-lee** [comment]
Thanks for the suggestions, @FMorschel ! I'll take them into account for the next survey (Q1 2024).

**Comment by jayoung-lee** [comment]
Hi @FMorschel ! The Q1 2024 survey was launched yesterday. 

1. The 'end of survey' message now says "If you have feedback about this survey, please file an issue at https://github.com/flutter/uxr/issues."
2. For a few APIs mentioned in the survey, I've added hyperlinks to their docs.
3. The survey is added to the banner docs.flutter.dev website. There will be a tweet tomorrow, too. Please spread the word yourself, too!

Thanks for the suggestions again.
