### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lulupointu** [flutter/uxr#12]
I would like to know if there is any road map for this project. I would be particularly interested in knowing how much time you estimate the study to take.

This would be very interesting as a plug-in developer since I would prefer to wait for the results to possibly address some  issues found by the study but at the same time people are looking for a stable version of my plugin.

**Comment by InMatrix** [comment]
Thanks for the question. I will update the [research overview](https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research) in the Wiki with some timing information about each planned activity this week. The immediate next step is #7. 

We'd love to include VRouter's API in our studies. Are you open to potentially changing VRouter's design based on study results?

**Comment by lulupointu** [comment]
Thank you very much!

Yes of course! Hence the question about the timing in fact 😉

**Comment by InMatrix** [comment]
I've posted target completion dates for the planned research activities in the [project overview](https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research). Please let me know if you have any questions. Thanks.

**Comment by lulupointu** [comment]
That's perfect, thanks!
