### ISSUE TITLE
Conduct a preliminary comparative analysis of router packages

### ISSUE THREAD

**Issue by jackkim9** [flutter/uxr#13]
Subtask to #10.

The goal is to conduct a preliminary analysis of router packages based on the navigation scenarios identified in #4 ([PDF](https://github.com/flutter/uxr/files/5953028/PUBLIC.Flutter.Navigator.API.Scenarios.-.Storyboards.pdf)).

List of packages for analysis (A-Z):

auto_route
beamer
flit-router
flouter
fluro
flutter_modular
page_router
qlevar_router
routemaster
vrouter

**Comment by pedromassango** [comment]
> fluro flutter_modular

(We need a break on this line)

**Comment by jackkim9** [comment]
This is the information I was able to get via documentations so far.  **This is meant to be work-in-progress.** Please feel free to drop a line if any of this information is inaccurate or you see a way to improve it. I would love to hear your thoughts on this, especially If you are the authors/contributors of these packages.

(Scroll to see all >)

  | auto_route | beamer | flit-router | flouter | fluro | flutter_modular | page_router | qlevar_router | vrouter
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Deep Linking - Path Parameters | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
Deep Linking - Query Parameters | ✅ | ✅ | ✅ | 🆇 | ✅ | ✅ | 🆇 | ✅ | ✅
Dynamic Linking | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
Validation (Login/Logout/Sign-up Routing) | 🆇 - route validation happens at the route pattern level, but no custom validators (e.g. check if id is valid before routing) | ✅ - BeamGuard | 🆇 - in TODO list | 🆇 | 🆇 - in TODO list | ✅ | ✅ - no way to specify "default" route when validation fails (e.g. go to login/ screen if user is logged out) | 🆇 | ✅- VNavigationGuard
Nested Routing | ✅ | 🆇 - in TODO list. Currently supports nested routing, but it's not yet synchronized with browsers | 🆇 | 🆇 - in TODO list | 🆇 - in TODO list | 🆇 | 🆇 | ✅ | ✅
Skipping Stacks | ✅ | ✅ | ✅ | 🆇 | 🆇 | 🆇 | ✅ | ✅ | 🆇
Custom Pages / Custom transition animations | 🆇 | 🆇 | ✅ | 🆇 | ✅ | ✅ | ✅ | 🆇 | ✅

**Comment by lulupointu** [comment]
Hi, I am the developer of vrouter. Thanks for your work it will definitely help every package to see where they can improve !

Speaking of, I see that you did not check the “Skipping Stacks” scenario for vrouter. I tried to follow the [Navigation scenario storyboards](https://github.com/flutter/uxr/files/5953028/PUBLIC.Flutter.Navigator.API.Scenarios.-.Storyboards.pdf) and [I did implement the scenario of skipping stack](https://github.com/flutter/uxr/issues/6#issuecomment-781730369)


<details>
 <summary>Here is the code for Skipping stacks </summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(
    VRouter(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        textButtonTheme: TextButtonThemeData(
          style: ButtonStyle(
            padding: MaterialStateProperty.all(EdgeInsets.all(20.0)),
            backgroundColor: MaterialStateColor.resolveWith((states) => Colors.black),
            textStyle: MaterialStateProperty.all(TextStyle(fontSize: 16, color: Colors.white)),
          ),
        ),
      ),
      routes: [
        VStacked(
          path: '/search',
          widget: SearchResultPage(),
          subroutes: [
            VStacked(
              path: ':productName',
              name: 'productPage',
              widgetBuilder: (context) => ProductPage(
                product: allProducts.firstWhere(
                  (product) =>
                      product.name ==
                      VRouteElementData.of(context).pathParameters['productName'],
                ),
              ),
            ),
          ],
        ),
        VStacked(
          // In parenthesis is a regExp which allows us to limit the productType
          //    - This is less verbose than creating multiple route
          //    - We can access the product type with the path parameter productType
          path: r'/:productType(book|shoes|pillow)',
          widgetBuilder: (context) => CategoryPage(
            products: allProducts
                .where((product) =>
                    productTypeToString(product.type) ==
                    VRouteElementData.of(context).pathParameters['productType'])
                .toList(),
          ),
          subroutes: [
            VStacked(
              path: ':productName',
              name: 'productPage',
              widgetBuilder: (context) => ProductPage(
                product: allProducts.firstWhere(
                  (product) =>
                      product.name ==
                      VRouteElementData.of(context).pathParameters['productName'],
                ),
              ),
            ),
          ],
        ),
        VRouteRedirector(path: ':_(.*)', redirectTo: '/search'),
      ],
    ),
  );
}

// We do not implement a search bar but only the page on which a user would be
// after he/she typed in a certain url
class SearchResultPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text('Dynamic linking')),
      ),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 30.0, horizontal: 20),
            child: Align(
              alignment: Alignment.topLeft,
              child: Text(
                'Here is the result for you search "stars":',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
            ),
          ),
          ProductList(
            products: allProducts.where((product) => product.name.contains("stars")).toList(),
          )
        ],
      ),
    );
  }
}

class ProductPage extends StatelessWidget {
  final Product product;

  const ProductPage({Key key, @required this.product}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text('Dynamic linking')),
        actions: [
          IconButton(
            icon: Icon(Icons.search),
            onPressed: () => VRouterData.of(context).push('/search'),
          )
        ],
      ),
      body: Hero(
        tag: product.name,
        child: Material(
          child: Container(
            color: productTypeColor(product.type),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('Type: ${productTypeToString(product.type)}'),
                  Text(product.name),
                  SizedBox(
                    height: 20,
                  ),
                  TextButton(
                    onPressed: () =>
                        VRouterData.of(context).push('/${productTypeToString(product.type)}'),
                    child: Text(
                      'See all ${productTypeToString(product.type)}',
                      style: TextStyle(color: Colors.white),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class CategoryPage extends StatelessWidget {
  final List<Product> products;

  const CategoryPage({Key key, @required this.products}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text('Dynamic linking')),
        actions: [
          IconButton(
            icon: Icon(Icons.search),
            onPressed: () => VRouterData.of(context).push('/search'),
          )
        ],
      ),
      body: ProductList(
        products: products,
      ),
    );
  }
}

class ProductList extends StatelessWidget {
  final List<Product> products;

  const ProductList({Key key, @required this.products}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Wrap(
        spacing: 20,
        runSpacing: 20,
        alignment: WrapAlignment.center,
        children: products,
      ),
    );
  }
}

class Product extends StatelessWidget {
  final String name;
  final ProductTypes type;

  const Product({Key key, @required this.name, @required this.type}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () => VRouterData.of(context).push(name),
      child: Hero(
        tag: name,
        child: Material(
          child: Container(
            height: 200,
            width: 200,
            color: productTypeColor(type),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('Type: ${productTypeToString(type)}'),
                  Text(name),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

enum ProductTypes { book, shoe, pillow }

Color productTypeColor(ProductTypes itemType) {
  switch (itemType) {
    case ProductTypes.book:
      return Colors.greenAccent;
    case ProductTypes.shoe:
      return Colors.redAccent;
    case ProductTypes.pillow:
      return Colors.blueAccent;
    default:
      return Colors.black;
  }
}

String productTypeToString(ProductTypes itemType) {
  switch (itemType) {
    case ProductTypes.book:
      return 'book';
    case ProductTypes.shoe:
      return 'shoes';
    case ProductTypes.pillow:
      return 'pillow';
    default:
      return 'unknown';
  }
}

final bookProducts = <Product>[
  Product(name: 'Book stars', type: ProductTypes.book),
  Product(name: 'old book', type: ProductTypes.book),
  Product(name: 'eBook', type: ProductTypes.book),
];

final shoesProducts = <Product>[
  Product(name: 'Shoes of stars', type: ProductTypes.shoe),
  Product(name: 'Only One Shoe', type: ProductTypes.shoe),
  Product(name: 'Shoe fleur', type: ProductTypes.shoe),
];

final pillowProducts = <Product>[
  Product(name: 'Best pillow', type: ProductTypes.pillow),
  Product(name: 'Pillow stars', type: ProductTypes.pillow),
  Product(name: 'This is not a pillow', type: ProductTypes.pillow),
];

final allProducts = <Product>[...bookProducts, ...shoesProducts, ...pillowProducts];
```

</details>

Maybe did I misunderstood what was described and the feature is missing from vrouter, could you explain me what was intended?

**Comment by tomgilder** [comment]
Hi @jackkim9, this is _very_ early days, but I've spent the last week working on an experimental router called Routemaster.

I haven't yet published this on pub.dev, but the code is here: https://github.com/tomgilder/routemaster

I've tried to specifically design it around the navigation scenarios in the storyboard document, and I've [documented how it supports them](https://github.com/tomgilder/routemaster/wiki/Routermaster-Flutter-scenarios).

I would love any feedback on the API, there's an (example app)[https://github.com/tomgilder/routemaster/blob/main/examples/mobile_app/lib/main.dart] which demos most of the scenarios.

Really loving the detailed UX research on this project, it's awesome!

**Comment by jackkim9** [comment]
Hi @lulupointu, thanks for pointing me to the snippet. I've updated the table to note this implementation. 

Hi @tomgilder, thanks for sharing your repo. I'll take a look at it soon!

**Comment by theweiweiway** [comment]
Hi @jackkim9 

I do believe that `AutoRoute` has validation with route guards. It's not quite in his documentation yet, but an example is here: https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/router/auth_guard.dart

Also, you can add custom transitions as seen here: https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route/example/lib/mobile/screens/user-data/routes.dart

**Comment by jackkim9** [comment]
Thanks @theweiweiway for sharing this. Will update the table accordingly.

**Comment by ntaoo** [comment]
@jackkim9 
Hello @jackkim9 , I'm the author of package:flit_router. I'd like to comment about the list above:
https://github.com/flutter/uxr/issues/13#issuecomment-789413420

- Nested Routing: I'm working on this feature right now in highest priority.
- Validation (Login/Logout/Sign-up Routing): I'm planning to implement this feature after implementing nested routing feature.

Both features are listed in the TODO list.
https://github.com/polyflection/flit_router#todo

**Comment by jackkim9** [comment]
Thanks, @ntaoo. I've updated the table to reflect your comment.

**Comment by Kleak** [comment]
Hey @jackkim9, flouter dev here.
As of now there only two point that I don't support.

The first is nested navigation, I have to do some research before going deeper on this point.
The second is validation, on this I also have to do some investigation.

Both need investigation and reflection on my side which will take me some time.


What I already support and is marked I don't here :

- query parameters
- skipping stack
- custom page / transition animation

**Comment by jackkim9** [comment]
@Kleak, thank you for the comment. I've updated the table accordingly.

**Comment by SchabanBo** [comment]
Hi all, qlevar_router here,
just an update for the table qlevar_router supports the validation:
Example
```dart
   QRoute(
        name: redirect,
        path: '/home',
        redirectGuard: (path) => AuthService().isAuthed? null : '/login')
```
and Custom Pages / Custom transition animations
```dart
   QRoute(
        name: itemsDetails,
        path: '/details',
        pageType: QRCupertinoPage(), // Here you can set the transition 
        onInit: () => print('onInit Items Details'),
        onDispose: () => print('onDispose Items Details'),
        page: (c) => ItemDetailsScreen())
    ]),
```
the supported types [QPage](https://github.com/SchabanBo/qlevar_router/blob/master/lib/src/qpages.dart)

**Comment by jackkim9** [comment]
Thanks @SchabanBo. I'll update the table.

**Comment by jacobaraujo7** [comment]
Hi @jackkim9 . 
Thanks for include flutter_modular!!
 
The Nested Routing is represented in doc, but with other name (RouterOutlet)
https://github.com/Flutterando/modular/tree/master/flutter_modular#routeroutlet

**Comment by jackkim9** [comment]
Thank you everyone for contributing to the preliminary comparative analysis of router packages. 

The table is now saved as a markdown file in our repo: https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis 

This analysis is not final, and this page is meant to be a living document. Please feel free to add or edit content by opening a pull request.


I appreciate that the authors of all of the packages mentioned above had a chance to provide feedback for the analysis. 


Our immediate next step is to conduct a more detailed evaluation (#7) of usability benefits and disadvantages based on code snippets (#9) provided by package authors based on the finalized navigator scenarios in #4. 

We have about 5 authors who expressed interest so far to participate in the next round and contribute code snippets for the usability evaluation. We will reach out to those authors with more detailed plans shortly.

**Comment by jackkim9** [comment]
Thank you, everyone, for contributing to the preliminary comparative analysis of router packages. 

The table is now saved as a markdown file in our repo: https://github.com/flutter/uxr/tree/master/nav2-usability/comparative-analysis 

This page will be a living document throughout our [study](https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research) and link to any code snippets provided by authors. Please feel free to add or edit content by opening a pull request.

We appreciate that the authors of all of the packages mentioned above had a chance to provide feedback for the analysis. Our immediate next step is to conduct a more detailed evaluation (#7) of usability benefits and disadvantages based on code snippets (#9) provided by package authors based on the soon-to-be-finalized navigator scenarios in #4. We have several authors who have expressed interest so far to participate in the next round and contribute code snippets for the usability evaluation. We will share a more detailed plan here: #9

**Comment by Gene-Dana** [comment]
Hi there ! I also made this comment at https://github.com/flutter/uxr/issues/7 

In terms of an abstracted nav 2.0 and usability, this package has helped me incredibly and I hope that it can be evaluated in this study: https://github.com/felangel/flow_builder

Realizing we can model app navigation with state was really powerful and with that clearly stated in the api, Login/Logout/Sign-up routing, nested routing, nested routing with dialog, manipulation of history stack, and skipping stacks navigation all are simplified, at least to me. 

In the package examples, there are snippets of all of these. I will gladly post them when the folder for this becomes available!

Also, the owner (Felix Angelov) is getting ready to add URL parsing support, which I believe will provide for deep and dynamic linking
