### ISSUE TITLE
Skip entire survey

### ISSUE THREAD

**Issue by damywise** [flutter/uxr#134]
I can skip the entire survey questions. Is this intentional? I feel like it shouldn't.

https://github.com/flutter/uxr/assets/25608913/ffe564ac-b716-4cad-b22e-9be6860eb059

**Comment by jayoung-lee** [comment]
Hi @damywise , thanks for bringing this up!

That's correct; skipping the entire survey is allowed. We prioritize giving respondents control over their experience to reduce fatigue and respect their time. Forced responses can sometimes encourage participants to provide random or careless answers, too.

We're aware that incomplete data is a possibility. To address this, we carefully design questions that are clear, concise, and minimize the urge to skip.

However, please let us know if there's any specific questions you found particularly difficult to answer. We're always working to improve our surveys and appreciate your input.

**Comment by damywise** [comment]
Seems like a non-issue then. Closing this, thanks for the response!
