### ISSUE TITLE
Flutter Plugin Crash Daemon Issue on IDE's (Android Studio and VSCode)

### ISSUE THREAD

**Issue by ImadBouirmane** [flutter/uxr#137]
Hi Team,

I've been encountering a persistent issue for over two weeks when launching Android Studio and VSCode on both Windows 11 and the latest macOS. The problem seems to be rooted in the Flutter SDK. I've reinstalled Flutter three times, but the issue persists.

Additional Information:
- Flutter Version: Latest
- Android Studio Latest Stable 
- VSCode Version: Latest Stable 

Error Message: 
![image](https://github.com/flutter/uxr/assets/8468212/8d339e55-a76a-4ab3-bcb4-2269fcaa8979)
![image](https://github.com/flutter/uxr/assets/8468212/9af76aca-5780-40c7-adf2-2a14900060fd)
![image](https://github.com/flutter/uxr/assets/8468212/132fdfc6-ca49-46fa-bd58-25fc185f8701)

Steps to Reproduce:
1. Launch the IDE 
2. Open Flutter Project root
3. Automatiaclly the crash come 

Logs/Stack Traces (if available):
[Error - 1:02:15 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:02:15 PM] The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 1:02:15 PM] Dart Analysis Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:02:15 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

Your assistance in resolving this matter is highly appreciated. Let me know if there's any additional information needed.

**Comment by rekire** [comment]
Wild guess this is the wrong repository. Check [flutter](https://github.com/flutter/flutter/issues) repository.

**Comment by parlough** [comment]
Thanks for issue! However, this is likely the wrong repository.

If this is still happening, can you open a new issue on the [Dart SDK repository](https://github.com/dart-lang/sdk/issues) with this information, the output of `flutter doctor -v`, and any information about the project(s) you are working on when this happens.
