### ISSUE TITLE
Populating Pages Attribute: Hardcoded or Dynamic?

### ISSUE THREAD

**Issue by idkq** [flutter/uxr#21]
## Problem

Today, in Nav 2.0, the order of appearance of the screens is dictated by the order of the objects of the `pages` attribute (accepts `List<Page>`) in the `Navigator` class. This creates a problem: as the number of screen grows, it becomes more and more difficult to manage which screen will appear in front of the other. The result is several `if`s each corresponding to a specific screen. Most nav APIs did not address this problem or followed option 1.

```dart
pages: [
  MaterialPage(child: BooksListScreen()),
  if (show404)
    MaterialPage(key: ValueKey('UnknownPage'), child: UnknownScreen())
  else if (_selectedBook != null)
    MaterialPage(child: BookDetailsScreen(book: _selectedBook))
   ... //many other ifs
],
```

### Option 1 - Hardcoded (compile time)

Keep as is: declare the order of the pages at compile time. One option to improve is to divide the screens in smaller scopes and to help keep it organized. **Pros**: order never changes; dart style. **Cons**: Developer needs to keep track of the order.

### Option 2 - Dynamic

Allow developer to add pages to a list without any order. Before the app loads (or at any other point in time) shuffle the pages to the correct order. **Pros**: Developer doesn't need to keep track of the order (the order could be inferred from child-parent URL for example). **Cons**: Small overhead to reshuffle screens at runtime. 

Example:

`PageOrder` is doing this reshuffle here. The logic of reordering can vary. For example it can follow the order of the URL structure.

```dart
Navigator(
  pages: [
     PageOrder( children:[
        MaterialPage(child: CategoryPage()),
        MaterialPage(child: ProductPage()),
        MaterialPage(child: MainPage()),      
        ... // many other pages
    ])
  ],
)
```

### Decision

Even if `pages` attribute will not be directly populated in the future framework/design of the new API we need to make a decision if the API itself will be doing this manually or 'automatically'. A lot of the design will be around this decision because if a dynamic model exist, there will be much more flexibility on how one can implement the API.

### EDIT: URL example

Here is an example where the list could be reshuffled to match the url structure based on the forward slash of the `urls` variable. To link the url with the page, there are many alternatives: pass as parameter to `PageOrder` constructor, create a new class in which each page would have a key or the URL itself, etc. 

```
urls = ['/main/', '/main/categoryPage/', '/main/categoryPage/productPage']
```

**Comment by nguyenxndaidev** [comment]
Honestly, I don't see any benefit of PageOrder. If I want to order pages, I just need to call sort method on a comparator (inline or extracted) and everything is done. Super simple already.

**Comment by idkq** [comment]
@nguyenxndaidev PageOrder was just an example which is doing exactly what you described - sorting. The question is should we have the order defined at compile time or runtime.

**Comment by nguyenxndaidev** [comment]
> @nguyenxndaidev PageOrder was just an example which is doing exactly what you described - sorting. The question is should we have the order defined at compile time or runtime.
> 
> Also, is not that simple since you need some logic to sort. The logic can be complex which is basically how each screen will appear at anytime in your app.

Sort method means runtime.
Without sort method, it's compile time.

**Comment by slovnicki** [comment]
> Developer doesn't need to keep track of the order.

But who is defining `PageOrder` logic? It seems you just moved the problem to a different place.

**Comment by idkq** [comment]
> > Developer doesn't need to keep track of the order.
> 
> But who is defining `PageOrder` logic? It seems you just moved the problem to a different place.

It could be inferred by the URL for example, based on the forward slash parent-child. There’s no way to do that with hardcoded logic.

**Comment by slovnicki** [comment]
Yes, that would be the most logical ordering. But ordering could also be whatever the developer wants so one way or another, the developer will need to define the ordering. If `PageOrder` provides some convenient way to do so, cool, but I don't consider this as a necessary part of navigation package. It could be a separate package that can help in ordering a list provided by URL (or something).

**Comment by idkq** [comment]
> that would be the most logical ordering...
> If PageOrder provides some convenient way to do so, cool

Exactly. It could be the default logic, if no other logic is implemented. The developer would be able to override the logic.

> I don't consider this as a necessary part of navigation package

My experience was that as you have more screens, having 20, 40 screens, managing the ordering is very difficult, so to me yes, it was 100% critical. Plus having 40 chained `if`s is not elegant and confusing to say the least, and I don't believe anyone would call it a good design. But open to other ways to solve this problem.

**Comment by slovnicki** [comment]
I see.

I was maybe too stuck with beamer's idea of separating stacks into smaller chunks. 

After more thought, this idea of having a wrapper that would order and filter pages seems like an interesting basis for a navigation package.

**Comment by idkq** [comment]
```dart
IndexedStack(children: [])
```

[Is 'recommended'](https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386) for Nav 1.0 + Bottom Navigator Bar.

I envision something similar for Pages.
