### ISSUE TITLE
Should we make routing snippets runnable from this repo?

### ISSUE THREAD

**Issue by InMatrix** [flutter/uxr#39]
I was trying to find an easy to to run the snippets in the [scenario-code folder](https://github.com/flutter/uxr/tree/master/nav2-usability/scenario-code). One way to do is is to turn this folder a Flutter project. I've published a branch to illustrate what it entails: https://github.com/flutter/uxr/tree/run_snippets/nav2-usability/scenario_code. All the snippets are moved into the lib folder of the project. 

Is it a good idea?

**Comment by nguyenxndaidev** [comment]
It would be nice if we can do it because it will encourage users running all scenarios of all packages without hesitation.
Additionally we can give links to run on dartpad.dev for all code snippets.

**Comment by InMatrix** [comment]
It seems that changing the scenario-code folder to a runnable demo can be useful. I can make this change after #34 is merged to avoid conflicts. 

DartPad.dev doesn't support packages yet, but there is some work being done towards that goal: https://github.com/dart-lang/dart-pad/issues/1813.

**Comment by InMatrix** [comment]
Closed by #42.
