### ISSUE TITLE
Scenario modifications for assessing API viscosity

### ISSUE THREAD

**Issue by InMatrix** [flutter/uxr#41]
[Viscosity](https://github.com/flutter/uxr/wiki/API-Usability-Evaluation-Guide#viscosity) is a dimension of API usability we try to assess in this research. Simply put, viscosity measures the ease of modifying code when the requirements have changed. Is the amount of code change out of proportion to the requirements change? Is there a “domino effect” when refactoring code for a seemingly small change in the app's routing behavior? 

To assess viscosity, we need to define a few modifications to our [navigation scenarios](https://github.com/flutter/uxr/blob/master/nav2-usability/storyboards/%5BPublic%5D%20Flutter%20Navigator%20Scenarios%20Storyboards%20v2.pdf). These modifications need to represent the kinds of changes developers would often run into when iterating on their apps. This issue is created to discuss those modifications. Here are some preliminary thoughts:

### Scenario: Deep linking by path parameter 
* Adding a new route (e.g., settings)
* Changing the path pattern (i.g., change ‘/books/’ to ‘/items/’ )

### Scneario: Login
* Splitting the sign-in screen into two steps, username and password.
* Adding a two-factor verification screen

### Nested routing
* Changing page transition animations between views in an inner route
* Moving code of an inner route to a separate library, so a separate team can work on it (discussed in #35)
* Unnesting a route (i.e. promoting a secondary section to a primary section)

**Comment by idkq** [comment]
Few more:

* Deleting/removing route
* Adding data parameters to the route (i.e. book/id:001)
* Adding routes to the navigation stack (example: when tap back, go back two screens)
* Changing variables that control stateful navigation when using declarative (see https://github.com/flutter/uxr/issues/15)

**Comment by nguyenxndaidev** [comment]
I think, we need a scenario to migrate a non-web version to web version.

**Comment by lulupointu** [comment]
@nguyenxndaidev agreed! That might be very important, even if this is not a migration but just a dev wanting to jump into web. The need to learn a lot of new ways to handle a package just to support web could be a pain.

**Comment by slovnicki** [comment]
@nguyenxndaidev agreed!
This might be out of scope for viscosity per se, so I suggest we open another issue for exploring the migration from "Navigator 1.0" to some package enabling "Navigator 2.0" (as most of them are supporing web by default already).

**Comment by nguyenxndaidev** [comment]
@slovnicki I don't think it's out of scope of viscosity. The measuring of modifications should start from a code which doesn't use the package, not just after using it.

**Comment by InMatrix** [comment]
@nguyenxndaidev Migrating from a mobile-only implementation to web is an important consideration. For the purpose of this study, we're going to limit the scope to changes in app behavior and leave changes in platforms as a separate factor. In future work, we should probably consider changes in form factors as well, e.g., adapting an app from mobile to desktop.

**Comment by InMatrix** [comment]
I moved this thread to the newly created Discussions section: https://github.com/flutter/uxr/discussions/51. Please continue the conversation there. Thank you.
