### ISSUE TITLE
[proposal] address missing features for flutter web in flutter/uxr

### ISSUE THREAD

**Issue by iapicca** [flutter/uxr#52]
I'm a great fan of the concept and the work done by the team and the community for [nav2-usability](https://github.com/flutter/uxr/tree/master/nav2-usability)
I'm also a fan of the initiative [suggested](https://github.com/dart-lang/sdk/issues/44876#issuecomment-774668083) by @rydmike and carried on by @osaxma of collecting [flutter web limitation](https://github.com/osaxma/FlutterWebLimitations)
so far (with the feeling that this list is just a fraction of the issues):
- [datetime precision limited to milliseconds](https://github.com/dart-lang/sdk/issues/44876)
- [dart sdk libraries not available](https://github.com/flutter/flutter/issues/39998)
- [flutter web not seo friendly ](https://github.com/flutter/flutter/issues/46789) and [doesn't support ads](https://github.com/flutter/flutter/issues/40376)
- [jsonEncode behavior](https://github.com/dart-lang/sdk/issues/45160)
- [doesn't support hot reload](https://github.com/flutter/flutter/issues/53041)
- [doesn't support grpc](https://github.com/flutter/flutter/issues/48054#issuecomment-571254564)
- [gif behavior](https://github.com/flutter/flutter/issues/78223)

plus all the `keyboard`, `mouse`  and other issues not specific to `web`

IMHO, how these issues are addressed should depend from devs feedback, 
for example in a recent [youtube conference](https://youtu.be/BsX9t69lKVw?t=11353) @mariamhas asks feedback about the use cases for flutter [web hot-reload](https://github.com/flutter/flutter/issues/53041)
@marwan-at-work and @nguyenxndaidev provided 2 valid use cases for flutter web hot-reload:
- [forms](https://github.com/flutter/flutter/issues/53041#issuecomment-822020615)
- [modal pop-up](https://github.com/flutter/flutter/issues/53041#issuecomment-822947237)

such a useful feedback could be "irretrievable" if not collected properly.

As a flutter developer I'm concerned about the future for flutter web, 
quoting @creativecreatorormaybenot 's [comment](https://github.com/flutter/flutter/issues/53041#issuecomment-821968320)  in reference to `hot reload for flutter web`

> The fact that Flutter Web does not support it as a stable platform should be a big red flag in terms of priority. If the priority is low because it seems like this is not feasible, you should at least give us an indication that it is not going to happen.

I feel in the same way and not just for `hot reload`, but for most (if not all) the missing features mentioned above
and often **_parity_** are considered `feature request` with low priority, but for devs these **_feel like bugs_**
(paraphrasing @gaaclarke  comment on a not-so-much tangentially related [issue](https://github.com/flutter/flutter/issues/32120#issuecomment-804380127))

these **_red flags_** might cause even flutter enthusiasts to looks somewhere else for web development (for [example](https://youtu.be/YHhC-7FVo7I)) 
this is a dangerous feedback loop

**_flutter web is not a priority_** => **_flutter web lacks features_** => **_few devs adopt flutter web_** =>  **_flutter web is not a priority_**

Collecting and analyzing developers feedback might break this loop

#### I wish the `missing features for flutter web` will be addressed in the same way as `nav2-usability`

thank you

**Comment by nguyenxndaidev** [comment]
> **_flutter web is not a priority_** => **_flutter web lacks features_** => **_few devs adopt flutter web_** =>  **_flutter web is not a priority_**

Nice quote 😄 !

**Comment by amorenew** [comment]
Hot-reload is a must feature for web developers 😭 🥺

**Comment by mariamhas** [comment]
Thank you for the feedback and pointing us to the web limitations outlined by @osaxma.

Feedback like this is very valuable so I appreciate you taking the time to share it.

While Flutter’s web support is now available in the stable channel, we don’t consider the work done. 

Leading up to the stable release, we did several research studies with early adopters using Flutter on the web as well as [surveys](https://medium.com/flutter/flutter-on-the-web-slivers-and-platform-specific-issues-user-survey-results-from-q3-2020-f8034236b2a8) to help us define the V1 stable release of Flutter’s web support. 

We are currently in the process of defining our priorities and future roadmap for Flutter on the web.

My main takeaway from your feedback is that you’d like to see the same transparency with our plans and research for Flutter on the web that we have done with the research for nav2.

I’m closing this issue, but will ensure that we address the points you made when we communicate our plans and conduct our research for Flutter on the web in the future. Stay tuned :)

Until then, the best way to provide the team feedback is to continue filing and upvoting issues in the flutter/flutter repo.

Thank you!
Mariam

**Comment by iapicca** [comment]
> [...] My main takeaway from your feedback is that you’d like to see the same transparency with our plans and research for Flutter on the web that we have done with the research for nav2. [...]

@mariamhas 
that is almost accurate, I do have a question that I feel being the true core of the issue;
for the current [road-map](https://github.com/flutter/flutter/wiki/Roadmap#web-and-desktop) for `web` and `desktop` states 
> For Web specifically, our focus will be on fidelity and performance, **_rather than new features_**

some, including myself, may feel that the [road-map could be more detailed](https://github.com/flutter/flutter/issues/71367), specifically 

### is parity across platform considered a new feature?

**Comment by mariamhas** [comment]
following up on this: I hope this blog post is the kind of roadmap you were looking for and addresses more specifically what our near term plans are. https://medium.com/flutter/flutter-whats-next-on-the-web-e0454bff964

**Comment by creativecreatorormaybenot** [comment]
thanks @mariamhas - the scrolling section in my mind is missing issues like https://github.com/flutter/flutter/issues/83368, i.e. if you are not using macOS and/or trackpads, the default scrolling behavior currently is not usable on some devices.

**Comment by rydmike** [comment]
Excellent article and progress on Flutter Web, thanks @mariamhas.

I noticed the infamous topic SEO was only fleetingly mentioned, what kind of strategy are you going with to tackle it?

## SEO Renderer
An interesting community approach that I found is the **seo_renderer** package: https://pub.dev/packages/seo_renderer

It can help a bit, you can wrap Text with TextRenderer, Links with LinkRenderer and Images in ImageRenderer. What does that do?

* On VM builds, nothing
* On Web it inserts the Text, Link, and image link alt name into the web page in normal divs, but only for search engine bots. When you test and verify in the browser you have to debug as a search engine crawler, to actually see them. For normal users they are not present as that would obviously mess up the web app.

It's not a perfect solution, but it can help to reduce the stress of not having any SEO at all from important text, links and images in your Flutter web app. Plus you can use it in cross platform VM builds too. 

It uses dart.html to do its magic, and sure, mixing it into Flutter is not ideal. As a disclaimer, I contributed to the project, but only minorly by showing the author how to do the conditional dart.html and wrappers so it is not even imported in VM builds, but can be still be used in same code base.

**Comment by rydmike** [comment]
@creativecreatorormaybenot it is definitely a strong possibility that it may be so.

Author is trying to find out if that is the case as well: 
* https://github.com/iamSahdeep/seo_renderer/issues/1
* https://support.google.com/webmasters/thread/115430508/will-this-be-considered-cloaking-or-anything-which-may-lead-to-penalising-my-site?hl=en

I've seen reports form using this package and getting good in SEO results, but I'm not sure either. It is indeed "a bit" like past cloaking.
