### ISSUE TITLE
Beamer loses filter when URL is provided in the browser

### ISSUE THREAD

**Issue by idkq** [flutter/uxr#69]
@slovnicki Do you mind checking it please

Filter is not working properly when URL is typed in the browser's navigation bar. 

<details>
  <summary>Repro</summary>
  
`flutter run -d Chrome -t lib/deeplink-queryparam/deeplink-queryparam_beamer.dart --web-port=51513`

Paste in browser bar and hit enter (TWICE - two times):

http://localhost:51513/#/?filter=land
http://localhost:51513/#/?filter=land (again)

Filters disappears
</details>

<details>
  <summary>Doctor</summary>
[✓] Flutter (Channel beta, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] Connected device (2 available)

• No issues found!
</details>

**Comment by slovnicki** [comment]
@idkq Thanks for noticing this!
I was unintentionally ignoring query parameters on initial route path `/`. It's fixed now and will be released in `v0.14.1`; https://github.com/slovnicki/beamer/commit/c6ad949996e05a5b0b25ea5f492acbb011a4c2e6
