### ISSUE TITLE
Provide common state to nested routes

### ISSUE THREAD

**Issue by oodavid** [flutter/uxr#72]
Our app often forwards data to "child" routes.

We'd prefer child routes to inherit data from parent routes.

## Example

Here we have an app to view and comment on user's photos:

```
/users/123
/users/123/photos
/users/123/photos/456
/users/123/photos/456/comments
```

On `/users/123` we access `user = User(123)` from the database and Provide it to the widget tree to render their profile.

On the "child" views we **also** want access to `user`. Currently we pass this data as props to the new screens. This works well, but starts to feel a little boilerplatey once you get quite deep.

You can imagine the data that `/users/123/photos/456/comments/678/likes` may want access to.

**Comment by InMatrix** [comment]
Cc a few package authors for their consideration / responses: @lulupointu @slovnicki @Milad-Akarie @ tomgilder.

**Comment by Milad-Akarie** [comment]
In auto_route you have easy access to inherited path params.

 ```
context.routeData.inhertiedPathParams;
```

**Comment by InMatrix** [comment]
Closing this issue since it's obsolete.
